channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=24.3.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==1.26.3
  - psutil==5.9.6
  - scikit-learn==1.4.1.post1
  - scipy==1.11.1
  - typing==3.7.4.3
name: mlflow-env
